DROP DATABASE IF EXISTS ejercicio1;
CREATE DATABASE ejercicio1;
USE ejercicio1;
DROP TABLE IF EXISTS ALUMNOS;
CREATE TABLE ALUMNOS(
	NIF VARCHAR(9) PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Apellido1 VARCHAR(20) NOT NULL,
	Apellido2 VARCHAR(20) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Sexo CHAR(1) NOT NULL,
	Fecha de Nacimiento DATE NOT NULL,
	Curso INT NOT NULL,
	FOREIGN KEY (Curso) REFERENCES CURSOS(id)
);

DROP TABLE IF EXISTS CURSOS;
CREATE TABLE CURSOS (
	id INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	Max_Alumn INT NOT NULL,
	Fecha_In DATE NOT NULL,
	Fecha_Fin DATE,
	Num_Horas INT,
	NIF_Profesor VARCHAR(9) NOT NULL,
	FOREIGN KEY (NIF_Profesor) REFERENCES PROFESORES(NIF)
);

DROP TABLE IF EXISTS PROFESORES;
CREATE TABLE PROFESORES(
	NIF VARCHAR(9) PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
	Apellido1 VARCHAR(20) NOT NULL,
	Apellido2 VARCHAR(20) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Titulación VARCHAR(300) NOT NULL,
	Salario_Mes8 DECIMAL(4,2) NOT NULL
);
