DROP DATABASE IF EXISTS PCL_jardineria;
CREATE DATABASE PCL_jardineria;
USE PCL_jardineria;

DROP TABLE IF EXISTS OFICINAS;
CREATE TABLE OFICINAS(
CODIGOOFICINA VARCHAR(10) PRIMARY KEY,
PAIS VARCHAR(50)  NOT NULL,
REGION VARCHAR(50) ,
CODIGOPOSTAL VARCHAR(10) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
LINEADIRECCION1 VARCHAR(50) NOT NULL,
LINEADIRECCION2 VARCHAR(50)
);

DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE EMPLEADOS(
CODIGOEMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO1 VARCHAR(50) NOT NULL,
APELLIDO2 VARCHAR(50),
EXTENSION VARCHAR(10) NOT NULL,
EMAIL VARCHAR(10) NOT NULL,
CODIGOOFICINA VARCHAR(10) NOT NULL,
CODIGOJEFE INT,
PUESTO VARCHAR(50),
FOREIGN KEY (CODIGOOFICINA) REFERENCES OFICINAS(CODIGOOFICINA) ON UPDATE CASCADE,
FOREIGN KEY (CODIGOJEFE) REFERENCES EMPLEADOS(CODIGOEMPLEADO) ON DELETE SET NULL ON UPDATE CASCADE
);



DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(
CODIGOCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOMBRECLIENTE VARCHAR(50) NOT NULL,
NOMBRECONTACTO VARCHAR(30),
APELLIDOCONTACTO VARCHAR(30),
TELEFONO VARCHAR(15) NOT NULL,
FAX VARCHAR(15) NOT NULL,
LINEADIRECCION1 VARCHAR(50) NOT NULL,
LINEADIRECCION2 VARCHAR(50) NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
REGION VARCHAR(50),
PAIS VARCHAR(50),
CODIGOPOSTAL VARCHAR(10),
CODIGOEMPLEADOREPVENTAS INT,
LIMITECREDITO DECIMAL (15,2),
FOREIGN KEY (CODIGOEMPLEADOREPVENTAS) REFERENCES EMPLEADOS(CODIGOEMPLEADO)
);

DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE PEDIDOS(
CODIGOPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
FECHAPEDIDO DATE NOT NULL,
FECHAESPERADA DATE NOT NULL,
FECHAENTREGA DATE,
ESTADO VARCHAR(15) NOT NULL,
COMENTARIOS TEXT,
CODIGOCLIENTE INT NOT NULL,
FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTES(CODIGOCLIENTE)ON UPDATE CASCADE
);

DROP TABLE IF EXISTS GAMASPRODUCTOS;
CREATE TABLE GAMASPRODUCTOS(
GAMA VARCHAR(50) PRIMARY KEY,
DESCRIPCIONTEXTO TEXT,
DESCRIPCIONHTML TEXT,
IMAGEN BLOB
);

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
CODIGOPRODUCTO VARCHAR(15) PRIMARY KEY,
NOMBRE VARCHAR(70) NOT NULL,
GAMA VARCHAR(50) NOT NULL,
DIMENSIONES VARCHAR(25),
PROVEEDOR VARCHAR(50),
DESCRIPCION TEXT,
CANTIDADENSTOCK SMALLINT NOT NULL,
PRECIOVENTA DECIMAL (15,2),
FOREIGN KEY (GAMA) REFERENCES GAMASPRODUCTOS(GAMA) ON UPDATE CASCADE
);

DROP TABLE IF EXISTS DETALLEPEDIDOS;
CREATE TABLE DETALLEPEDIDOS(
CODIGOPEDIDO INT NOT NULL,
CODIGOPRODUCTO VARCHAR(15) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIOUNIDAD DECIMAL (15,2) NOT NULL,
NUMEROLINEA SMALLINT NOT NULL,
FOREIGN KEY (CODIGOPEDIDO) REFERENCES PEDIDOS(CODIGOPEDIDO) ON UPDATE CASCADE,
FOREIGN KEY (CODIGOPRODUCTO) REFERENCES PRODUCTOS(CODIGOPRODUCTO)ON UPDATE CASCADE,
PRIMARY KEY (CODIGOPEDIDO,CODIGOPRODUCTO)
);

DROP TABLE IF EXISTS PAGOS;
CREATE TABLE PAGOS(
CODIGOCLIENTE INT NOT NULL,
FORMAPAGO VARCHAR(40) NOT NULL,
IDTRANSACCION VARCHAR(50),
FECHAPAGO DATE NOT NULL,
CANTIDAD DECIMAL (15,2) NOT NULL,
FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTES(CODIGOCLIENTE) ON UPDATE CASCADE,
PRIMARY KEY(CODIGOCLIENTE, IDTRANSACCION)
);

/*TABLA CLIENTES ALTERS*/
ALTER TABLE CLIENTES CHANGE TELEFONO TELEFONOMOVIL VARCHAR(15) NOT NULL;
ALTER TABLE CLIENTES ADD COLUMN TELEFONOFIJO VARCHAR(15) NOT NULL AFTER TELEFONOMOVIL;
ALTER TABLE CLIENTES CHANGE LINEADIRECCION1 DIRECCION1 VARCHAR(50) NOT NULL;
ALTER TABLE CLIENTES CHANGE LINEADIRECCION2 DIRECCION2 VARCHAR(50) NOT NULL;
ALTER TABLE CLIENTES ALTER PAIS SET DEFAULT "SPAIN";
ALTER TABLE CLIENTES ADD CONSTRAINT CONST_PAIS_CLIENT CHECK (PAIS IN ("USA","SPAIN","FRANCE","AUSTRALIA","UNITED KINGDOM"));
/*DARÁ ERROR SI EL INDICE NO EXISTE PORQUE SEMANTICAMENTE NO EXISTE*/
DROP INDEX idx_TELEFONOMOVIL ON CLIENTES; 
CREATE INDEX idx_TELEFONOMOVIL ON CLIENTES (TELEFONOMOVIL);
DROP VIEW IF EXISTS V_CLIENTES;
CREATE VIEW V_CLIENTES AS SELECT PAIS, NOMBRECLIENTE, TELEFONOMOVIL FROM CLIENTES ORDER BY PAIS ASC;

/*TABLA EMPLEADOS ALTERS*/
ALTER TABLE EMPLEADOS ADD COLUMN TELEFONO VARCHAR(15) NOT NULL AFTER APELLIDO2;
ALTER TABLE EMPLEADOS ADD CONSTRAINT CONST_PUESTO CHECK (PUESTO IN ("DIRECTOR GENERAL","SUBDIRECTOR MARKETING","SUBDIRECTOR VENTAS","SECRETARIA","REPRESENTANTE VENTAS","DIRECTOR OFICINA"));
DROP VIEW IF EXISTS V_EMPLEADOS;
CREATE VIEW V_EMPLEADOS AS SELECT APELLIDO1, APELLIDO2, NOMBRE, PUESTO FROM EMPLEADOS ORDER BY APELLIDO1 ASC;

/*TABLA OFICINAS*/
ALTER TABLE OFICINAS CHANGE LINEADIRECCION1 DIRECCION1 VARCHAR(50) NOT NULL;
ALTER TABLE OFICINAS CHANGE LINEADIRECCION2 DIRECCION2 VARCHAR(50) NOT NULL;
ALTER TABLE OFICINAS ADD CONSTRAINT CONST_PAIS_OFI CHECK (PAIS IN ("SPAIN","USA","UNITED KINGDOM","FRANCE","AUSTRALIA","JAPAN"));
DROP VIEW IF EXISTS V_OFICINAS;
CREATE VIEW V_OFICINAS AS SELECT PAIS, TELEFONO, DIRECCION1 FROM OFICINAS ORDER BY PAIS ASC;

/*ALTER GAMAPRODUCTOS*/
ALTER TABLE GAMASPRODUCTOS RENAME TO GAMA;

/*USUARIOS*/
DROP USER IF EXISTS adminPCL;
CREATE USER adminPCL IDENTIFIED BY "pableras";
grant all on PCL_jardineria.* to adminPCL;

DROP USER IF EXISTS usuarioPCL;
CREATE USER usuarioPCL IDENTIFIED BY "macarrones";
grant select on PCL_jardineria.* to usuarioPCL;



select * from alumno where id = 1;
select * from alumno where teléfono = 692735409;
select * from alumno where es_repetidor = "sí";
select * from alumno where es_repetidor = "no";
select * from alumno where fecha_nacimiento < '1993/01/01';
select * from alumno where fecha_nacimiento > '1994/01/01';
select * from alumno where fecha_nacimiento > '1994/01/01' and es_repetidor = "no";
select * from alumno where fecha_nacimiento between '1998-01-01' and '1998-12-31';
/*otra forma*/
select * from alumno where year(fecha_nacimiento) = 1998;

select * from alumno where fecha_nacimiento not between '1998-01-01' and '1998-12-31';
/*otra forma*/
select * from alumno where year(fecha_nacimiento) != 1998;

/* % es igual a 'cualquier cosa' */
/* _ es igual a 1 espacio con cualquier cosa' */
select * from alumno where apellido1 like '%chez';
select * from alumno where apellido1 like 'S%';
select * from alumno where apellido1 like '______z';
select * from alumno where apellido1 like '_a%'; 
/*NO ES IGUAL A */
select * from alumno where apellido1 like '%a%'; 
/* esta devuelve todas las que contengan la a, en cualquier posicion */

select * from alumno where char_length(apellido1) = 9; /*cuenta chars*/
select * from alumno where length(apellido1) = 9; /*cuenta bytes*/

select * from alumno where apellido1 like "abc%" escape "%";
select * from alumno where apellido1 like "abc\%"; /* viene a ser lo nmismo */